import { Floorplan } from './floorplan.model';
import { Geocode } from './geocode.model';
import { Parking } from './parking.model';
import { PetInfo } from './pet-info.model';
import { SchoolsInfo } from './schools-info.model';

export interface Property {
  listID: number;
  propertyID: number;
  yearBuilt: number;
  yearRenovated: number;
  name: string;
  streetAddress: string;
  neighborhood: string;
  phone: string;
  city: string;
  adminFee: number;
  appFee: number;
  url: string;
  favorite: boolean;
  notes: string;
  specials: string;
  parking: Parking;
  schoolsInfo: SchoolsInfo;
  petInfo: PetInfo;
  floorplans: Floorplan[];
  highValueAmenities: string[];
  unitAmenities: string[];
  propertyAmenities: string[];
  geocode: Geocode;
  photos: string[];
  section8: boolean;
  studentHousting: boolean;
  seniorHousing: boolean;
  officeHours: any;
  numUnits: number;
  email: any;
  role: string;
  management: any;
  managementOffices: any[];
  regionalName: any;
  regionalPhone: any;
  regionalEmail: any;
  onsiteManager: any;
  order: number;
  state: string;
  pets: boolean;
  washerDry: string;
  photo: string;
  highestSentCommissions: number;
  proximity: number;
  paidUtilities: string[];
}
